In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "RollNo": [101,102,103,104,105,106,107,108],
    "Name": ["Amit","Neha","Rahul","Priya","Rohan","Kavya","Arjun","Simran"],
    "Department": ["BCA","BCA","MCA","BCA","MCA","MCA","BCA","MCA"],
    "Age": [20,21,22,20,23,22,21,24],
    "Marks": [85,92,67,78,88,95,55,73]
})

In [29]:
#1
df

   RollNo    Name Department  Age  Marks
0     101    Amit        BCA   20     85
1     102    Neha        BCA   21     92
2     103   Rahul        MCA   22     67
3     104   Priya        BCA   20     78
4     105   Rohan        MCA   23     88
5     106   Kavya        MCA   22     95
6     107   Arjun        BCA   21     55
7     108  Simran        MCA   24     73

In [30]:
#2
df.head(3)

   RollNo   Name Department  Age  Marks
0     101   Amit        BCA   20     85
1     102   Neha        BCA   21     92
2     103  Rahul        MCA   22     67

In [31]:
#3
df.tail(2)

   RollNo    Name Department  Age  Marks
6     107   Arjun        BCA   21     55
7     108  Simran        MCA   24     73

In [32]:
#4
df.shape

(8, 5)

In [33]:
#5
df.columns

Index(['RollNo', 'Name', 'Department', 'Age', 'Marks'], dtype='str')

In [34]:
#6
df.dtypes

RollNo        int64
Name            str
Department      str
Age           int64
Marks         int64
dtype: object

In [35]:
#7
df["Name"]

0      Amit
1      Neha
2     Rahul
3     Priya
4     Rohan
5     Kavya
6     Arjun
7    Simran
Name: Name, dtype: str

In [36]:
#8
df[["Name", "Marks"]]

     Name  Marks
0    Amit     85
1    Neha     92
2   Rahul     67
3   Priya     78
4   Rohan     88
5   Kavya     95
6   Arjun     55
7  Simran     73

In [37]:
#9
df[df["Marks"]>80]

   RollNo   Name Department  Age  Marks
0     101   Amit        BCA   20     85
1     102   Neha        BCA   21     92
4     105  Rohan        MCA   23     88
5     106  Kavya        MCA   22     95

In [38]:
#10
df[df["Marks"]<70]

   RollNo   Name Department  Age  Marks
2     103  Rahul        MCA   22     67
6     107  Arjun        BCA   21     55

In [39]:
#11
df[df["Marks"].between(70,90)]

   RollNo    Name Department  Age  Marks
0     101    Amit        BCA   20     85
3     104   Priya        BCA   20     78
4     105   Rohan        MCA   23     88
7     108  Simran        MCA   24     73

In [40]:
#12
df[df["Department"]== "BCA"]

   RollNo   Name Department  Age  Marks
0     101   Amit        BCA   20     85
1     102   Neha        BCA   21     92
3     104  Priya        BCA   20     78
6     107  Arjun        BCA   21     55

In [28]:
#13
df[(df["Department"]== "MCA") & (df["Marks"]>80)]

   RollNo   Name Department  Age  Marks
4     105  Rohan        MCA   23     88
5     106  Kavya        MCA   22     95

In [27]:
#14
df[df["Age"]>21]

   RollNo    Name Department  Age  Marks
2     103   Rahul        MCA   22     67
4     105   Rohan        MCA   23     88
5     106   Kavya        MCA   22     95
7     108  Simran        MCA   24     73

In [43]:
#15
df["Marks"].mean()

np.float64(79.125)

In [44]:
#16
df["Marks"].max()

np.int64(95)

In [46]:
#17
df["Marks"].min()

np.int64(55)

In [47]:
#18
df["Marks"].median()

np.float64(81.5)

In [50]:
#19
(df["Marks"]>75).sum()

np.int64(5)

In [54]:
#20
df[df["Department"]== "BCA"] ["Marks"].mean()

np.float64(77.5)

In [57]:
#21
df[df["Department"]== "MCA"] ["Marks"].mean()

np.float64(80.75)

In [59]:
#23
df["Bonus"]=5

In [60]:
#24
df["Final Marks"]= df["Marks"] + df["Bonus"]

In [61]:
df

   RollNo    Name Department  Age  Marks  Bonus  Final Marks
0     101    Amit        BCA   20     85      5           90
1     102    Neha        BCA   21     92      5           97
2     103   Rahul        MCA   22     67      5           72
3     104   Priya        BCA   20     78      5           83
4     105   Rohan        MCA   23     88      5           93
5     106   Kavya        MCA   22     95      5          100
6     107   Arjun        BCA   21     55      5           60
7     108  Simran        MCA   24     73      5           78

In [62]:
#25
df["Result"] = "Fail"
df.loc[df["Marks"] >= 40, "Result"] = "Pass"

In [63]:
df

   RollNo    Name Department  Age  Marks  Bonus  Final Marks Result
0     101    Amit        BCA   20     85      5           90   Pass
1     102    Neha        BCA   21     92      5           97   Pass
2     103   Rahul        MCA   22     67      5           72   Pass
3     104   Priya        BCA   20     78      5           83   Pass
4     105   Rohan        MCA   23     88      5           93   Pass
5     106   Kavya        MCA   22     95      5          100   Pass
6     107   Arjun        BCA   21     55      5           60   Pass
7     108  Simran        MCA   24     73      5           78   Pass